apiVersion: v1
kind: Service
metadata:
  name: unoclave-backend-service
spec:
  selector:
    app: unoclave-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
